### ISSUE TITLE
consider releasing a snapshot release

### ISSUE THREAD

**Issue by bennyandresen** [lambdaisland/regal#15]
hello lambdaisland,

I know you wrote it's not yet officially out, but according to your blogpost[1] you consider regal stable enough to start incorporating it into projects.

For those of us that are on leiningen where you can't just do a git dependency on a project that isn't itself using leiningen (excuse me if I'm wrong) we need to set up a private maven repository and that's a hassle. 

Would you consider releasing a -SNAPSHOT release for us poor souls?
(Or I could dive in and switch my own projects to clj deps)

Thanks in advance

[1]  https://lambdaisland.com/blog/2020-06-05-open-source-update-may-2020

**Comment by plexus** [comment]
Regal is now out on Clojars, version `0.0.80`, refer to the README to see which parts are considered stable, and which are considered alpha.
