### ISSUE TITLE
Unicode Character Classes unsupported

### ISSUE THREAD

**Issue by tanzoniteblack** [lambdaisland/regal#16]
```clojure
regal/*flavor*
=> :java9
(regal-parse/parse #"\p{InCombiningDiacriticalMarks}+")
=> [:+ [:lambdaisland.regal.parse/not-implemented [:UnicodeCharacterClass "p" "{InCombiningDiacriticalMarks}"]]]
(regal-parse/parse #"\p{Alpha}")
=> [:lambdaisland.regal.parse/not-implemented [:UnicodeCharacterClass "p" "{Alpha}"]]
(regal-parse/parse #"\p{InGreek}")
=> [:lambdaisland.regal.parse/not-implemented [:UnicodeCharacterClass "p" "{InGreek}"]]
```

**Comment by plexus** [comment]
Hi @tanzoniteblack , please don't open issues for every regex feature. Do open issues if we are unable to parse a regex for which there is regal syntax.

**Comment by tanzoniteblack** [comment]
@plexus ah, apologies. I misread the request for issues in the blog post about what kind of issues you wanted filed

**Comment by alysbrooks** [comment]
We definitely welcome PRs expanding Regal's support for features like Unicode classes, but it's unlikely to be a priority.
