### ISSUE TITLE
Java mutating flags unsupported

### ISSUE THREAD

**Issue by tanzoniteblack** [lambdaisland/regal#17]
```clojure
(regal-parse/parse #"(?i)t{3}")
=> [:cat [:lambdaisland.regal.parse/not-implemented [:MutatingMatchFlags [:MatchFlagsExpr "i"]]] [:repeat "t" 3]]
```

**Comment by plexus** [comment]
That is correct, we neither generate nor parse flags at this time.

**Comment by alysbrooks** [comment]
We definitely welcome PRs expanding Regal's support for features like flags, but it's unlikely to be a priority, so I'm closing it for now.
