### ISSUE TITLE
Feature suggestion: Add support for re2

### ISSUE THREAD

**Issue by lumimies** [lambdaisland/regal#24]
I have a project which requires the same expression to run in both normal JDK and on a remote host using [re2](https://github.com/google/re2j).
I already wrote the needed code to add re2 support, and can restructure it into a pull request.

Is this of interest to the project?

**Comment by plexus** [comment]
Hi @lumimies, I wasn't aware of Re2 but it does sound interesting. What would Regal support look like exactly? I'm guessing it uses the same pattern syntax as Java, so is it just a matter of passing the compiled pattern string to an Re2 constructor? In that case maybe an example in the README would suffice.

If we do want to add support we'll have to make sure it's BYO (bring-your-own), so no hard dependency on Re2. We have support for that in our build tooling via `:aliases-as-optional-deps`, (example from [data-printers](https://github.com/lambdaisland/data-printers/blob/main/bin/proj#L9)).

**Comment by lumimies** [comment]
The syntax is a bit different. Specifically:
* Character escapes using `\uFFFF` aren't supported, but instead `\x{FFFF}`
* `\cX` is not supported
* Lookahead, lookbehind, atomic are not supported
* `\v` means vertical tab, not any vertical space
* `\R` is not supported (and probably can't be perfectly emulated, because of lack of lookaround?)

I only added support for the syntax, not for `lambdaisland.regal/regex` and `lambdaisland.regal/compile`, so I'm not sure what that would look like.

I'm not compiling or running the regex on the local JVM, but sending it to some service that speaks re2 (Google's BigQuery actually).

**Comment by alysbrooks** [comment]
This is finished. Thanks again!
