### ISSUE TITLE
Data-based test fails on :any sometimes

### ISSUE THREAD

**Issue by alysbrooks** [lambdaisland/regal#28]
```
FAIL in lambdaisland.regal-test/data-based-tests (regal_test.cljc:120)
:any -> "." generated strings match the given pattern :any
expected: (re-find (regal/regex form) s)
  actual: (not (re-find #"." "\r"))
```

`:any` is not supposed to match newlines, so I'm not sure it should be generating this test case with the linefeed character, which is a part of line separators on Windows (`\r\n`) and doesn't get much use otherwise, AFAIK.

**Comment by plexus** [comment]
There was indeed an issue with the generator, note to self: don't confuse `\r` and `\n` with `\return` and `\newline`.
