### ISSUE TITLE
Move test.check to dev/test alias dependencies

### ISSUE THREAD

**Issue by borkdude** [lambdaisland/regal#3]
It would be nice to get test.check out of the way for users who aren't using the generators from this library. There are a couple of things to be considered:

- Let users supply the dependency on test.check themselves (spec takes this approach). 
- In the "core" namespace `lambaisland.regal` do not depend on the generators namespace, so it won't load the generators.
- When people want to use the generators they are going to require lambdaisland.regal.generators themselves.

All of the above combined would mean that no changes have to happen in the generators namespace and would probably yield simpler code than implementing something like dynaload (which doesn't really work with CLJS) or other workarounds.

**Comment by plexus** [comment]
This was already changed on master, I moved the test-check dependency to an alias. People can bring their own if they need it.

**Comment by borkdude** [comment]
Doesn't seem to be the case:

https://github.com/lambdaisland/regal/blob/468195aa81fcbd73c2c8e566c57411f359950a23/deps.edn#L3

Also, just moving the dep to an alias doesn't solve the last two things I mentioned. The lambdaisland.regal namespace still has a hard indirect dependency on test.check.

**Comment by plexus** [comment]
You're right, I'll fix this. Thanks for the report!
