### ISSUE TITLE
Unexpected type returned

### ISSUE THREAD

**Issue by lvh** [lambdaisland/regal#47]
I got the following result, which I did not expect:

```clojure
[(type (regal/regex [:alt "a" "b"]))
 (type (regal/pattern [:alt "a" "b"]))]

;; => [java.util.regex.Pattern java.lang.String]
```

This is on GraalVM (graalvm-22.2.0+java17) on Linux amd64, running `  lambdaisland/regal {:mvn/version "0.0.143"}`.

**Comment by alysbrooks** [comment]
I'm not sure which of the return types is unexpected, but this is the intended behavior. See the docstrings for [`regex`](https://cljdoc.org/d/lambdaisland/regal/CURRENT/api/lambdaisland.regal#regex) and [`pattern`](https://cljdoc.org/d/lambdaisland/regal/CURRENT/api/lambdaisland.regal#pattern).

I could see how you might expect `pattern` to return a `java.util.regex.Pattern`, but this library's convention is to use "pattern" to refer to regular expressions in string form, as opposed to the compiled patterns. I suppose "regex" could be interpreted as meaning the regular expression in string form, but using "regex" to mean the compiled regex form is also one of our conventions. Ideas for making this clearer are welcome!

**Comment by lvh** [comment]
Ah, my mistake, thank you! I was indeed too focused on the Java term. It made sense once I considered e.g. JS.

I'm not sure how to make this clearer, unfortunately.
